### ISSUE TITLE
Would not "Module '${id}' specified twice" fire in a non-circular code too?

### ISSUE THREAD

**Issue by klesun** [Hashbrown777/typescript-native#1]
https://github.com/Hashbrown777/typescript-native/blob/365a3f78193eb3fed74c10dbe09cf27d0f19b231/compile.js#L11

Hi. Reading through your code, noticed this codition and got curious: would not it throw error on a completely normal dependency, like some `Util.ts` used in two different files?

**Comment by klesun** [comment]
Oh, sorry, never mind, this check seems to only make sure that there are no duplicate `<script>` imports...

**Comment by klesun** [comment]
Do I get it right, does your lib only work with typescript in `<script>` tags? Does it not support importing ts files from withing the code itself, not specifying each module in the html file?

**Comment by Hashbrown777** [comment]
It might not!

I built it with the goal of "emulating running the ts compiler locally".
So just as you would need to download resources to your local filesystem, you need to declare them in your html.

I like how yours seems to more be the goal of "es6 web modules but in ts!" and is a better direction for this generally for other people I think.

It would be awesome to include the ability of embedded scripts.
E.g. `<script id="modulename">export const yes :string = 'I'm typescript!';</script>`
For feature parity of oldschool js (imagine the wonders of live ts script injection too!), which is the only thing this does that [klesun/ts-browser](https://github.com/klesun/ts-browser) is missing (I dont even think es6 modules can do that).

I abuse/shim AMD modules for that, but what I could do instead is compile and shim embedded scripts only, and have the rest of the ts compile to es6 modules instead, which would be so elegant.
